name: my_portfolio_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.3
  lottie: ^3.0.0
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  go_router: ^13.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true

  assets:
    - assets/
