name: my_portfolio_flutter
description: "Monir's portfolio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  lottie: ^3.1.3
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  animated_text_kit: ^4.2.2
  scroll_pos: ^0.5.0
  lecle_bubble_timeline: ^0.0.1+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
